### ISSUE TITLE
pcloudcc: command not found

### ISSUE THREAD

**Issue by stefanpetrov** [pcloudcom/console-client#1]
Hello,

Ubuntu 14.04 LTS: I've run apt-get command `sudo apt-get install cmake zlib1g-dev libboost-system-dev libboost-program-options-dev libpthread-stubs0-dev libfuse-dev`  , then I've cloned repo and from the repo folder have tried `pcloudcc -h`. Result is `pcloudcc: command not found`. What I'm doing wrong?

Thank you

**Comment by Pilotat** [comment]
After cloning the repo, inside the repo you should run:

```
cmake .
make
```

If you installed all the necessary dependencies, you should have pcloudcc binary in the same folder, which you can execute by running

`./pcloudcc -h`

**Comment by pcloudcom** [comment]
Hello,
Complete steps to build form the repo are:
sudo apt-get install cmake zlib1g-dev libboost-system-dev libboost-program-options-dev libpthread-stubs0-dev libfuse-dev git
mkdir console-client
git clone https://github.com/pcloudcom/console-client.git ./console-client/
cd ./console-client/pCloudCC/
cd lib/pclsync/
make clean
make fs
cd ../mbedtls/
cmake .
make clean
make
cd ../..
cmake .
make 
sudo make install
ldconfig
pcloudcc -u username -p

Best regards,
Ivan Stoew
