### ISSUE TITLE
Stuck at LOGIN_REQUIRED with Raspberry Pi 4

### ISSUE THREAD

**Issue by mort74** [pcloudcom/console-client#115]
I managed to compile the code after removing the -mtune=core2 option in pclsync's Makefile and installing curl.h (with "apt install libcurl4-gnutls-dev").
But now, after entering the password, nothing happens after "Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED". The program's just stuck until I cancel it with Ctrl-C. There also doesn't seem to be some logfile or debug parameter to get more information.
So, any idea what could be wrong and how to fix it?

**Comment by vivasteve** [comment]
Same issue here with AUR version https://aur.archlinux.org/packages/pcloudcc/
Have tried 3 different pcloud clients on AUR - all fail with some issue apparently with pcloud API
Non windows/mac people also want to use pcloud ;)

**Comment by ChuckNorrison** [comment]
this console client is US only, you need to tweak and rebuild. Related to this https://github.com/pcloudcom/console-client/issues/130

**Comment by pcloudcom** [comment]
Console client is fixed to work with both US and EU accounts now. And with any future locations we might add.

**Comment by vivasteve** [comment]
Thanks, it's working for me now

**Comment by mort74** [comment]
A big and belated thanks from me as well.
Just two minor issues:
- I had to remove the -mtune=core2 options in the pclssync/Makefile to build it, maybe there's a more elegant solution?
- startcrypto in the -k console crashes. However, starting the demon with -c and entering the crypto password works fine.
