### ISSUE TITLE
Build Error: recipe for target 'CMakeFiles/pcloudcc_lib.dir/pclsync_lib.cpp.o' failed

### ISSUE THREAD

**Issue by jeff47** [pcloudcom/console-client#117]
When issuing make in the directory pCloudCC, I get a fatal error.  Builds in the subdirectories were successful.

Ubuntu 18.04, kernel 5.4.12-050412-generic.

`[  9%] Building C object CMakeFiles/sqlite3.dir/lib/sqlite/sqlite3.c.o
[ 18%] Linking C static library libsqlite3.a
[ 18%] Built target sqlite3
Scanning dependencies of target pcloudcc_lib
[ 27%] Building CXX object CMakeFiles/pcloudcc_lib.dir/pclsync_lib_c.cpp.o
[ 36%] Building CXX object CMakeFiles/pcloudcc_lib.dir/pclsync_lib.cpp.o
In file included from /usr/src/console-client/pCloudCC/pclsync_lib.cpp:36:0:
/usr/src/console-client/pCloudCC/lib/pclsync/pcompat.h:95:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/boost/smart_ptr/detail/local_sp_deleter.hpp:20:0,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:1158,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/src/console-client/pCloudCC/pclsync_lib.cpp:42:
/usr/include/boost/smart_ptr/detail/local_counted_base.hpp: In member function ‘void boost::detail::local_counted_base::add_ref()’:
/usr/include/boost/smart_ptr/detail/local_counted_base.hpp:67:9: error: ‘__builtin_assume’ was not declared in this scope
         __builtin_assume( local_use_count_ >= 1 );
         ^~~~~~~~~~~~~~~~
/usr/include/boost/smart_ptr/detail/local_counted_base.hpp:67:9: note: suggested alternative: ‘__builtin_abs’
         __builtin_assume( local_use_count_ >= 1 );
         ^~~~~~~~~~~~~~~~
         __builtin_abs
CMakeFiles/pcloudcc_lib.dir/build.make:86: recipe for target 'CMakeFiles/pcloudcc_lib.dir/pclsync_lib.cpp.o' failed
make[2]: *** [CMakeFiles/pcloudcc_lib.dir/pclsync_lib.cpp.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'CMakeFiles/pcloudcc_lib.dir/all' failed
make[1]: *** [CMakeFiles/pcloudcc_lib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by glenndm1000** [comment]
I've the same issue.  I tried a number of suggestions describe here and elsewhere without success.
Any news on how to get past this?  

I'm trying to build on debian 10 with allow_other enabled  (see issue  #56)

**Comment by glenndm1000** [comment]
with the help and  commit 18/02/20 by pcloudcom (I think), compilation and build is now successful.

On debian buster, additionally packages to the build steps are needed:
apt-get install build-essential fuse

to allow access by others:  ( from info gleaned here)
- add option allow_other       in lib/pclsync/pfs.c      (before build)
- uncomment allow_other     in /etc/fuse.conf

run pcloudcc with daemon option 

HTH

**Comment by jeff47** [comment]
Looks good!  Compiles and run, will do some more testing later.
