### ISSUE TITLE
Where is the CLI mount point?

### ISSUE THREAD

**Issue by Slikkit** [pcloudcom/console-client#125]
Hello. 

I run the command `sudo pcloudcc -n -u user@gmail.com -p -s -o -m /mnt/`. 

Where can I access the mount point?

**Comment by Ihon75** [comment]
mkdir /pCloud
sudo pcloudcc -n -u user@gmail.com -p -s -o -m /pCloud

voila, Mountpoint /pCloud

**Comment by Ryders** [comment]
@Slikkit to the benefit of helping the @pcloudcom team - if this issue is no longer a problem, would you please consider closing this issue? 👍
