### ISSUE TITLE
Build step ldconfig requires sudo

### ISSUE THREAD

**Issue by danielhz** [pcloudcom/console-client#127]
In the `README.md`, A current [build step](https://github.com/pcloudcom/console-client/blob/master/README.md#build-steps) says `ldconfig`, but it has to be `sudo ldconfig`.

**Comment by Ratteler** [comment]
Anyone verify this? I tried that and my reinstall still didn't work,

ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied

Sudo ldconfig returns no error, but then pCloudCC give me an init error.

I deleted everything but the libfuze-dev stuff because I don't know where to find it

I'm on Twister OS which is a for of Raspberry Pi OS.
It worked the first time, but I didn't realize the -p command had no password argument, and always requires manual entry of the password. I was trying to figure out how to make pcloud start on boot,

**Comment by blackjackshellac** [comment]
I installed into /usr/local and had to verify that /usr/local/lib was in /etc/ld.so.conf.d/use_local.conf, it may also be in /etc/ld.so.conf. You can run ldd on the binary to ensure that it is finding all of the shared libs,

```
$ ldd /usr/local/bin/pcloudcc 
	linux-vdso.so.1 (0x00007ffd555dc000)
	libpcloudcc_lib.so => /usr/local/lib/libpcloudcc_lib.so (0x00007f035403d000)
	libfuse.so.2 => /lib64/libfuse.so.2 (0x00007f0353ffa000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0353fd8000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0353fbe000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0353fb7000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f0353dc7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0353c7f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0353c64000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0353a9a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f03543cf000)
```

**Comment by Ratteler** [comment]
Here is where I bomb out,

pi@raspberrypi:~/console-client/pCloudCC $ ldd /usr/local/bin/pcloudcc
	linux-vdso.so.1 (0xbef80000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0xb6f00000)
	libpcloudcc_lib.so => /usr/local/lib/libpcloudcc_lib.so (0xb6bce000)
	libfuse.so.2 => /lib/arm-linux-gnueabihf/libfuse.so.2 (0xb6b92000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6b68000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb6b3d000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6b2a000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb69e3000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb6961000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6934000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb67e6000)
	/lib/ld-linux-armhf.so.3 (0xb6f15000)

**Comment by ChuckNorrison** [comment]
https://github.com/pcloudcom/console-client/pull/137

**Comment by pcloudcom** [comment]
README is updated with this info.
