### ISSUE TITLE
Compiling this stuff is a nightmare and at the end does not work anyway...

### ISSUE THREAD

**Issue by grhawk** [pcloudcom/console-client#14]
Hello,

I successfully compiled your code in a raspbian OS installed on a raspberry-pi. 

Step to compile:
----------------------
 * Switch to the `electron` branch.
 * Always substitute the `-mtune=core2` option with `-mtune=native` in all `CFLAGS` (within the used Makefiles). I think this could be the default since `native` should optimize the code for the actual architecture.
* Also add the option `-I../../../` to the same `CFLAGS` if the code looks for `gitcommit.h`.
* compile all the following codes inside the `lib` folder:
  - `pclsync`
  - `powerlay-linux`
  - `mbedtls`
  Install all the missing library while compiling (packages: `libssl-dev` and `libcrypto-dev`).
* Eventually... if you are lucky enough a `cmake .` followed by a `make` will be enough to get the executable. 

Probably I forgot some step.

However:
-------------
BTW, when I try to run
```
$ pcloudcc -u "myuser" -p 
```

I write the password but it stop at `loggin in` and then nothing happen.... Moreover there is no difference if I write the right password or a wrong one.... :(

**Comment by pcloudcom** [comment]
Hi,
Just tested on Rosberry Pi:

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

Checking out electron branch is definitely very bad idea. Console client will not work properly from electron branch, it's purpose is the .so file. Checkout the latest master branch there are some important build fixes there.  Following step work like a charm:

sudo apt-get install cmake zlib1g-dev libboost-system-dev libboost-program-options-dev libpthread-stubs0-dev libfuse-dev git
mkdir console-client
git clone https://github.com/pcloudcom/console-client.git ./console-client/
cd ./console-client/pCloudCC/
cd lib/pclsync/
make clean
make fs
cd ../mbedtls/
cmake .
make clean
make
cd ../..
cmake .
make 
sudo make install
ldconfig
pcloudcc -u username -p

Best regards,
Ivan Stoev

**Comment by grhawk** [comment]
With instruction is much much better... ;)

Thank you very much,
Riccardo

**Comment by dwavrant** [comment]
Hi, 

 I have a compilation error with the cmake . command : 
`volumio@volumio:~/console-client/pCloudCC$ cmake .
CMake Error at /usr/share/cmake-3.6/Modules/FindBoost.cmake:1772 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_program_options

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


-- Configuring incomplete, errors occurred!
`

of course, i installed boost package with `sudo apt-get install libboost-all-dev` command

The command ` dpkg -l | grep boost` return this list : 
`ii  libboost-all-dev                       1.55.0.2                           armhf        Boost C++ Libraries development files (ALL) (default version)
ii  libboost-atomic-dev:armhf              1.55.0.2                           armhf        atomic data types, operations, and memory ordering constraints (default version)
ii  libboost-atomic1.55-dev:armhf          1.55.0+dfsg-3                      armhf        atomic data types, operations, and memory ordering constraints
ii  libboost-atomic1.55.0:armhf            1.55.0+dfsg-3                      armhf        atomic data types, operations, and memory ordering constraints
ii  libboost-chrono-dev:armhf              1.55.0.2                           armhf        C++ representation of time duration, time point, and clocks (default version)
ii  libboost-chrono1.55-dev:armhf          1.55.0+dfsg-3                      armhf        C++ representation of time duration, time point, and clocks
ii  libboost-chrono1.55.0:armhf            1.55.0+dfsg-3                      armhf        C++ representation of time duration, time point, and clocks
ii  libboost-context-dev:armhf             1.55.0.2                           armhf        provides a sort of cooperative multitasking on a single thread (default version)
ii  libboost-context1.55-dev:armhf         1.55.0+dfsg-3                      armhf        provides a sort of cooperative multitasking on a single thread
ii  libboost-context1.55.0:armhf           1.55.0+dfsg-3                      armhf        provides a sort of cooperative multitasking on a single thread
ii  libboost-coroutine-dev                 1.55.0.2                           armhf        provides a sort of cooperative multitasking on a single thread (default version)
ii  libboost-coroutine1.55-dev:armhf       1.55.0+dfsg-3                      armhf        provides a sort of cooperative multitasking on a single thread
ii  libboost-date-time-dev:armhf           1.55.0.2                           armhf        set of date-time libraries based on generic programming concepts (default version)
ii  libboost-date-time1.55-dev:armhf       1.55.0+dfsg-3                      armhf        set of date-time libraries based on generic programming concepts
ii  libboost-date-time1.55.0:armhf         1.55.0+dfsg-3                      armhf        set of date-time libraries based on generic programming concepts
ii  libboost-dev:armhf                     1.55.0.2                           armhf        Boost C++ Libraries development files (default version)
ii  libboost-exception-dev:armhf           1.55.0.2                           armhf        library to help write exceptions and handlers (default version)
ii  libboost-exception1.55-dev:armhf       1.55.0+dfsg-3                      armhf        library to help write exceptions and handlers
ii  libboost-filesystem-dev:armhf          1.55.0.2                           armhf        filesystem operations (portable paths, iteration over directories, etc) in C++ (default version)
ii  libboost-filesystem1.55-dev:armhf      1.55.0+dfsg-3                      armhf        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-filesystem1.55.0:armhf        1.55.0+dfsg-3                      armhf        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-graph-dev:armhf               1.55.0.2                           armhf        generic graph components and algorithms in C++ (default version)
ii  libboost-graph-parallel-dev            1.55.0.2                           armhf        generic graph components and algorithms in C++ (default version)
ii  libboost-graph-parallel1.55-dev        1.55.0+dfsg-3                      armhf        generic graph components and algorithms in C++
ii  libboost-graph-parallel1.55.0          1.55.0+dfsg-3                      armhf        generic graph components and algorithms in C++
ii  libboost-graph1.55-dev:armhf           1.55.0+dfsg-3                      armhf        generic graph components and algorithms in C++
ii  libboost-graph1.55.0:armhf             1.55.0+dfsg-3                      armhf        generic graph components and algorithms in C++
ii  libboost-iostreams-dev:armhf           1.55.0.2                           armhf        Boost.Iostreams Library development files (default version)
ii  libboost-iostreams1.55-dev:armhf       1.55.0+dfsg-3                      armhf        Boost.Iostreams Library development files
ii  libboost-iostreams1.55.0:armhf         1.55.0+dfsg-3                      armhf        Boost.Iostreams Library
ii  libboost-locale-dev:armhf              1.55.0.2                           armhf        C++ facilities for localization (default version)
ii  libboost-locale1.55-dev:armhf          1.55.0+dfsg-3                      armhf        C++ facilities for localization
ii  libboost-locale1.55.0:armhf            1.55.0+dfsg-3                      armhf        C++ facilities for localization
ii  libboost-log-dev                       1.55.0.2                           armhf        C++ logging library (default version)
ii  libboost-log1.55-dev                   1.55.0+dfsg-3                      armhf        C++ logging library
ii  libboost-log1.55.0                     1.55.0+dfsg-3                      armhf        C++ logging library
ii  libboost-math-dev:armhf                1.55.0.2                           armhf        Boost.Math Library development files (default version)
ii  libboost-math1.55-dev:armhf            1.55.0+dfsg-3                      armhf        Boost.Math Library development files
ii  libboost-math1.55.0:armhf              1.55.0+dfsg-3                      armhf        Boost.Math Library
ii  libboost-mpi-dev                       1.55.0.2                           armhf        C++ interface to the Message Passing Interface (MPI) (default version)
ii  libboost-mpi-python-dev                1.55.0.2                           armhf        C++ interface to the Message Passing Interface (MPI), Python Bindings (default version)
ii  libboost-mpi-python1.55-dev            1.55.0+dfsg-3                      armhf        C++ interface to the Message Passing Interface (MPI), Python Bindings
ii  libboost-mpi-python1.55.0              1.55.0+dfsg-3                      armhf        C++ interface to the Message Passing Interface (MPI), Python Bindings
ii  libboost-mpi1.55-dev                   1.55.0+dfsg-3                      armhf        C++ interface to the Message Passing Interface (MPI)
ii  libboost-mpi1.55.0                     1.55.0+dfsg-3                      armhf        C++ interface to the Message Passing Interface (MPI)
ii  libboost-program-options-dev:armhf     1.55.0.2                           armhf        program options library for C++ (default version)
ii  libboost-program-options1.55-dev:armhf 1.55.0+dfsg-3                      armhf        program options library for C++
ii  libboost-program-options1.55.0:armhf   1.55.0+dfsg-3                      armhf        program options library for C++
ii  libboost-python-dev                    1.55.0.2                           armhf        Boost.Python Library development files (default version)
ii  libboost-python1.55-dev                1.55.0+dfsg-3                      armhf        Boost.Python Library development files
ii  libboost-python1.55.0                  1.55.0+dfsg-3                      armhf        Boost.Python Library
ii  libboost-random-dev:armhf              1.55.0.2                           armhf        Boost Random Number Library (default version)
ii  libboost-random1.55-dev:armhf          1.55.0+dfsg-3                      armhf        Boost Random Number Library
ii  libboost-random1.55.0:armhf            1.55.0+dfsg-3                      armhf        Boost Random Number Library
ii  libboost-regex-dev:armhf               1.55.0.2                           armhf        regular expression library for C++ (default version)
ii  libboost-regex1.55-dev:armhf           1.55.0+dfsg-3                      armhf        regular expression library for C++
ii  libboost-regex1.55.0:armhf             1.55.0+dfsg-3                      armhf        regular expression library for C++
ii  libboost-serialization-dev:armhf       1.55.0.2                           armhf        serialization library for C++ (default version)
ii  libboost-serialization1.55-dev:armhf   1.55.0+dfsg-3                      armhf        serialization library for C++
ii  libboost-serialization1.55.0:armhf     1.55.0+dfsg-3                      armhf        serialization library for C++
ii  libboost-signals-dev:armhf             1.55.0.2                           armhf        managed signals and slots library for C++ (default version)
ii  libboost-signals1.55-dev:armhf         1.55.0+dfsg-3                      armhf        managed signals and slots library for C++
ii  libboost-signals1.55.0:armhf           1.55.0+dfsg-3                      armhf        managed signals and slots library for C++
ii  libboost-system-dev:armhf              1.55.0.2                           armhf        Operating system (e.g. diagnostics support) library (default version)
ii  libboost-system1.55-dev:armhf          1.55.0+dfsg-3                      armhf        Operating system (e.g. diagnostics support) library
ii  libboost-system1.55.0:armhf            1.55.0+dfsg-3                      armhf        Operating system (e.g. diagnostics support) library
ii  libboost-test-dev:armhf                1.55.0.2                           armhf        components for writing and executing test suites (default version)
ii  libboost-test1.55-dev:armhf            1.55.0+dfsg-3                      armhf        components for writing and executing test suites
ii  libboost-test1.55.0:armhf              1.55.0+dfsg-3                      armhf        components for writing and executing test suites
ii  libboost-thread-dev:armhf              1.55.0.2                           armhf        portable C++ multi-threading (default version)
ii  libboost-thread1.55-dev:armhf          1.55.0+dfsg-3                      armhf        portable C++ multi-threading
ii  libboost-thread1.55.0:armhf            1.55.0+dfsg-3                      armhf        portable C++ multi-threading
ii  libboost-timer-dev:armhf               1.55.0.2                           armhf        C++ wall clock and CPU process timers (default version)
ii  libboost-timer1.55-dev:armhf           1.55.0+dfsg-3                      armhf        C++ wall clock and CPU process timers
ii  libboost-timer1.55.0:armhf             1.55.0+dfsg-3                      armhf        C++ wall clock and CPU process timers
ii  libboost-tools-dev                     1.55.0.2                           armhf        Boost C++ Libraries development tools (default version)
ii  libboost-wave-dev:armhf                1.55.0.2                           armhf        C99/C++ preprocessor library (default version)
ii  libboost-wave1.55-dev:armhf            1.55.0+dfsg-3                      armhf        C99/C++ preprocessor library
ii  libboost-wave1.55.0:armhf              1.55.0+dfsg-3                      armhf        C99/C++ preprocessor library
ii  libboost1.55-dev:armhf                 1.55.0+dfsg-3                      armhf        Boost C++ Libraries development files
ii  libboost1.55-tools-dev                 1.55.0+dfsg-3                      armhf        Boost C++ Libraries development tools
`

So libboost-program-options seems to be installed.

So, I don't understand what's wrong

TY
