### ISSUE TITLE
Does this work with Apps / Client secrets?

### ISSUE THREAD

**Issue by 2chilled** [pcloudcom/console-client#148]
Hi,

using pcloud API one is able to automate some day to day tasks without having to authenticate with user creds. For my current home automation project console-client would be quite handy because all I need to do is push some files to pcloud after they were uploaded to local FS via FTP. So if that local FS would be a pcloud mount my job would be done. The only requirement that's left is can I auth via Client secret somehow? I think I know the answer already but wanted to ask so I can be sure.

**Comment by pcloudcom** [comment]
After logging in once your password is saved and can be omitted for subsequent uses.
