### ISSUE TITLE
Where are my files ?

### ISSUE THREAD

**Issue by pcerne** [pcloudcom/console-client#164]
Thanks for this project !
Seems to work but, there is a but 
In the cli view I can find all files, and folder's size are correct. 
In the web view, I **can see all folders**, but they are empty. No file inside...

And I can't download anything.

Do you have any idea ?

Thanks

**Comment by pcerne** [comment]
Shame on me, only a cache browser issue...

Forget about this.

**Comment by samusz** [comment]
@pcerne May be close this issue then ?
