### ISSUE TITLE
The startup command doesn't seem to be working

### ISSUE THREAD

**Issue by 3att3** [pcloudcom/console-client#165]
The pcloudcc works fine when I start it manually ( pcloudcc -u example@myemail.com -d ) but putting it in a .sh file and executed it with crontab ( Added: @reboot /path/to/file.sh ).

How can I start pcloudcc at startup?

**Comment by ebouda33** [comment]
Use service or systemctl of your linux distribution
Tutorial 
https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples

for use pcloudcc -u [example@myemail.com](mailto:example@myemail.com) -d whithout typing Password
like this :

echo 'YourPassword' | pcloudcc -u your mail -p -d -m mountPointVolume(/mnt/pcloud)
This line in rc.local for example

**Comment by 3att3** [comment]
@ebouda33 Thanks a lot for the help!

Okay, this is what I did if anyone whats to do it this way, or fix any security mistakes I have done.

After installing and check that pcloudcc works I saved the password to keep it out of my pcloud.sh file ( bellow )

**Comment by 3att3** [comment]
accidentally closed it before commending. I will write down my steps and close the thread again.

@ebouda33 Thanks allot for the help!

**Comment by 3att3** [comment]
My steps are as follows: 

I created the **pcloud.sh** file. You can have it wherever you like, mine is in **/home/user/startupCommands/**

pcloud.sh
`
#! /bin/sh
echo "[PASSWORD]" | pcloudcc -u [MY@EMAIL.COM] -m /home/user/pcloud
`
the -m /home/user/pcloud is where I wanted to mount my pcloud drive.


Then I created the service file (pcloud.service) in the /etc/systemd/system/

pcloud.service
`
[Service]
User=[MY_USER]
Group=[MY_USER]
ExecStart=/home/user/startupCommands/pcloud.sh
Restart=on-failure
[Install]
WantedBy=multi-user.target
`

After that I executed the following commands
`sudo systemctl enable pcloud`

if you don't want to reboot your system then execute the following command as well
`sudo systemctl start pcloud`

and that is it!

**Comment by gasilva** [comment]
The pcloud script works like a charm when in the command line...
In Service, it is not working...no message of error.

When I restart the computer, the pCloudDrive does not appear in Nautilus.

**Comment by gasilva** [comment]
I found the solution...

The pcloud.service must be:[Service]
```
[Service]
User=parallels
Group=parallels
Type=simple
RemainAfterExit=yes
Restart=on-failure
ExecStart=/home/parallels/startup/pcloud.sh

[Install]
WantedBy=multi-user.target
```
