### ISSUE TITLE
Sync only one dir from the web disk

### ISSUE THREAD

**Issue by nelson777** [pcloudcom/console-client#17]
I have several folders in my on-line account. I want to sync only one. Is this possible ? 

I saw that in pCloud web page, on pCloud settings => Linked Accounts there is a line once I run the client on my server for the first time:

pclcmd	Anton Batenev [abbat]	/ (root)	All Files, Full Access

So if I could change "/(root) All Files, Full Access" to only /bkp it would be awesome. 

I searched a lot in the source-code trying to find the line where this is configured but couldn't find it. If you could just point to me in the source code where this is configured, I'll alter myself.

Thanks.

**Comment by pcloudcom** [comment]
Hello,
It is still not possible with the console client. Use full featured official one and add a "Sync". There is a feature request and when we have some time we will add the sync command until then use official client.

Best regards,
Ivan Stoev
