### ISSUE TITLE
got "init failed" when trying to mount pCloud to /backup

### ISSUE THREAD

**Issue by baijianpeng** [pcloudcom/console-client#18]
I want to use pCloud as a remote backup storage. So I followed your instructions in REAMDE and managed to installed it.

Then I ran following command:

`pcloudcc -u joomlagate@gmail.com  -m /backup`

And got following result:

> pCloud console client v.2.0.1
> init failed

I think "init failed" means something wrong. But what is wrong? How to mount pCloud as a "local folder" in my Ubuntu server so that my VestaCP can save "local backup" package there?

Thank you.

**Comment by pcloudcom** [comment]
two clients running

**Comment by baijianpeng** [comment]
understand now. Thank you.
