### ISSUE TITLE
Where is the best location to place the folder "console-client"?

### ISSUE THREAD

**Issue by baijianpeng** [pcloudcom/console-client#19]
I noticed that in your README tutorial about this console-client script, the first command after installing dependencies is:

`mkdir console-client`

However, I have no idea in which directory should I run this command? That is to say, where is the best location to place the folder "console-client"?

By default, if I only input the command:

`# cd`

I am in /root directory. Do you mean I should create this folder "console-client" in **/root** directory?

If /root is NOT the best place, then which directory is the best place?

I know I can create folder "console-client" in almost anywhere, but I think there should be one place which is the best choice. So please tell me what is that? I am a very newbie of Linux .

Thank you.

**Comment by baijianpeng** [comment]
Today I tried to place the folder "console-client" inside /usr/local/sbin/pcloud directory, and then start to follow your "Build Steps", but failed when running "cmake ." command:

>  CMake Error at CMakeLists.txt:2 (project):
>   No CMAKE_CXX_COMPILER could be found.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
>   to the compiler, or to the compiler name if it is in the PATH.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/usr/local/sbin/pcloud/console-client/pCloudCC/CMakeFiles/CMakeOutput.log".
> See also "/usr/local/sbin/pcloud/console-client/pCloudCC/CMakeFiles/CMakeError.log".

So this may indicate that your current building script does not allow custom location for your "console-client" installation.

Could you please improve this script so that we can intall it in /usr/local/sbin folder?

Thank you.

**Comment by pcloudcom** [comment]
There is a install rule in the make file. It is placing the executable in the best location. Use it.

best regards,
Ivan Stoev

**Comment by baijianpeng** [comment]
OK, thank you.
