### ISSUE TITLE
psyncgui and pcloudcc config conflict?

### ISSUE THREAD

**Issue by cchalk** [pcloudcom/console-client#2]
Hi,

If I use the psyncgui to configure my account then pcloudcc will say "Init failed." when trying to log in to the account.

When I delete the .pcloud folder in my home directory that was created by psyncgui and then try to log in to my account again using pcloudcc then everything works as expected.

Other than that pcloudcc is working great, thanks for the great tool.

**Comment by ivanivanovstoev** [comment]
Hello,
"Init failed." message indicates that other client is working at the moment. Running two pCloud clients at the same time is not allowed. You have to stop the psyncgui client first. You can do this, either from the tray icon or by finding and killing psyncgui process useing kill -9 command and then forcefully unmount the file-system performing: umount -f ~/pCloudDrive
