### ISSUE TITLE
Arguments to -p ignored

### ISSUE THREAD

**Issue by zibberzoo** [pcloudcom/console-client#20]
Arguments to -p appear to be ignored.  I am always prompted to enter my password.  Is this behavior intentional?  If so, then how can I automate this cli to connect to pcloud?  If not, then how might I get the -p argument to work?  (I have compiled the cli on a Raspberry Pi 2 running Ubuntu Server 16.04.)

**Comment by pcloudcom** [comment]
Hello,
Use -p with combination of -s to store the password. After successful authentication and storing you can simply use only -u and -d if you wish. Password may not be passed in command line this is a security issue.
Best regards,
Ivan Stoev

**Comment by zibberzoo** [comment]
Unfortunately, arguments to -p are being ignored with or without -s.  Even with -s, after manually entering the password, the password is not saved.
