### ISSUE TITLE
feature request: a single line automatic installer instead of multiple commands

### ISSUE THREAD

**Issue by baijianpeng** [pcloudcom/console-client#21]
I noticed that in your official instrucitons of "Build steps", before the last step "pcloudcc -u username -p", there are 16 separate steps to be executed one after one:

```

1. sudo apt-get install cmake zlib1g-dev libboost-system-dev libboost-program-options-dev libpthread-stubs0-dev libfuse-dev git
2. mkdir console-client
3. git clone https://github.com/pcloudcom/console-client.git ./console-client/
4. cd ./console-client/pCloudCC/
5. cd lib/pclsync/
6. make clean
7. make fs
8. cd ../mbedtls/
9. cmake .
10. make clean
11. make
12. cd ../..
13. cmake .
14. make
15. sudo make install
16. ldconfig

```

However, we can see that in these 16 commands, no one is "user specific", they are absolutely the SAME commands on any server. So, why not just combine them into a single batch installer file (pcloud-builder.sh)?

If you make such an "automatic installer file", then server admin can just run ALL of above 16 commands by input and run a single line of command like:

`wget -O  https://github.com/pcloudcom/console-client/pcloud-builder.sh | bash`

Don't you think this is better?

After the builder script being executed, then the user can run the last command which requires username and password.

Thank you.

**Comment by pcloudcom** [comment]
This is not install it is a build procedure. There are .deb and .rpm packages in "Other distributions" section, which are a single line install, if they work for you. The are a bit old but this is an open source software feel free to produce new one and submit a pull request. 

Best regards,
Ivan Stoev
