### ISSUE TITLE
not returned to command prompt after I enter my password

### ISSUE THREAD

**Issue by baijianpeng** [pcloudcom/console-client#22]
Ok, finally I successfully finished the "Build steps" , but for the last step. after I enter my password, there returned several lines and then halt, no error message, no command prompt either:

```
root@ubuntu:/usr/local/sbin/pcloud/console-client/pCloudCC# pcloudcc -u joomlagate@gmail.com  -p -s
pCloud console client v.2.0.1
Please, enter password
Down: Everything Downloaded| Up: Everything Uploaded, status is LOGIN_REQUIRED
logging in
Down: Everything Downloaded| Up: Everything Uploaded, status is CONNECTING
Down: Everything Downloaded| Up: Everything Uploaded, status is SCANNING
event1073741824
event1073741825
Down: Everything Downloaded| Up: Everything Uploaded, status is READY
```

What should I do now? Just wait? Or use "Ctrl + C" to terminate it?

I think this is a bug of your script. It should return to command prompt if it finished the former command.

**Comment by pcloudcom** [comment]
Hello,
You must use -d option. -h for more options.
Best regards,
Ivan Stoev

**Comment by baijianpeng** [comment]
But, in your "Build steps" , the last step is exactly:

`pcloudcc -u username -p`

There is no "-d" argument in this command. I was just following it.

Maybe you need to update the instructions?

Thank you.
