### ISSUE TITLE
README.md needs build instrucctions

### ISSUE THREAD

**Issue by choman** [pcloudcom/console-client#3]
The README.md needs build instructions.  I ran cmake under the pcloud\* dir and nothing happened.

I ended up installing the Debian deb file on ubuntu 16.04 as a result.

**Comment by Pilotat** [comment]
You should install all the necessary dependencies as described in the README:

`sudo apt-get install cmake zlib1g-dev libboost-system-dev libboost-program-options-dev libpthread-stubs0-dev libfuse-dev`

After that clone the repo and inside you should run:

```
cmake .
make
```

You should have pcloudcc binary in the same folder, which you can execute by running:

./pcloudcc -h

**Comment by pcloudcom** [comment]
Hi,
Done they are added. 
Best regards,
Ivan Stoev
