### ISSUE TITLE
probleme compil

### ISSUE THREAD

**Issue by ebouda33** [pcloudcom/console-client#55]
on make fs in  lib/pclsync/
pdevice_monitor.c:338:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
<builtin>: recipe for target 'pdevice_monitor.o' failed
make: *** [pdevice_monitor.o] Error 1

how i found libudev.h

**Comment by ebouda33** [comment]
ok i install libudev-dev

**Comment by omarpiani** [comment]
needed for Ubuntu 14.04 and 16.04
