### ISSUE TITLE
possible to use pcloudcc in fstab ?

### ISSUE THREAD

**Issue by ebouda33** [pcloudcom/console-client#56]
i want to mount my plcoud in fstab how to do this
for all user

**Comment by ebouda33** [comment]
i make some modification in 
/lib/pclsync/pfs.c:3318:  fuse_opt_add_arg(&args, "-oauto_unmount");
i add  fuse_opt_add_arg(&args, "-oallow_others");

and it s work fine
it s hack becareful for security

but done

**Comment by brockshort** [comment]
on my debian 9 system the fuse option is allow_other not allow_others . that being said the solution works well. I suspected this option was not used in the source code but i would have never known where to add it. How did you know where those fuse options were being implemented? im assuming it didn't require cat ./*|grep "fuse_opt"

**Comment by ebouda33** [comment]
Like in my comment
Search file i make some modification in
/lib/pclsync/pfs.c line 3318

**Comment by coreyman2000** [comment]
does this still work ? im trying this today but cant find that file to modify

**Comment by milsanore** [comment]
> does this still work ? im trying this today but cant find that file to modify
this is the file:
https://github.com/pcloudcom/console-client/blob/master/pCloudCC/lib/pclsync/pfs.c#L3417
