### ISSUE TITLE
How did it works?

### ISSUE THREAD

**Issue by fohnbit** [pcloudcom/console-client#97]
Hello,

how does the sync is working?

I have 3 folders, which I want to sync:
folder1
folder2
folder3

So I have to add a new mount folder and copy this 3 folder in there? But did I have then the files twice on my HDD?

Or should I start pCloudcc 3 times and mount the 3 original folder?

Thank you!

**Comment by fohnbit** [comment]
update:
the mount folder is from "pCloud.fs" ... so all Files are stored in "pCloud.fs"?
Where is the location on my linux system?

It´s because of local backups ... If I add a mount point and copy from one folder all in this pCloud mount folder, then I have the files twice on my hdd, right?

**Comment by blackjackshellac** [comment]
Mount should be in your home directory,
```
mount | grep pCloud.fs
```
synced folders are only cached in the pCloud.fs directory, so not everything is duplicated.  On the graphical client I have 5GB of on disk cache.

**Comment by fohnbit** [comment]
ok, perfect. Thank you!
